---
apiVersion: v1
metadata:
  labels:
    app.kuberentes.io/name: {{ include "owsec.name" . }}
    helm.sh/chart: {{ include "owsec.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "owsec.fullname" . }}-certs
kind: Secret
type: Opaque
data:
  {{- range $key, $value := .Values.certs }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
